export enum NotificationMessageEnum {
  NOTIFICATION_MESSAGE_SYNC_COMPLETED,
  NOTIFICATION_MESSAGE_PASTED,
  NOTIFICATION_MESSAGE_SONG_COMPLETED,
  SAVE_COMPLETED,
  TRACK_LOADED,
  TRACK_UPDATED,
}
