image:
  file: .gitpod.Dockerfile

tasks:
  - name: prepare project
    init: |
      npm install
      gp sync-done bundle
  - name: run serve
    init: gp sync-await bundle
    command: npm run start
    openMode: tab-after
  - name: run test watch
    init: gp sync-await bundle
    command: |
      npm run prepare:test
      npm run test:watch
    openMode: tab-after

ports:
  - port: 3000

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: false
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: false
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to true)
    addComment: true
    # add a "Review in Gitpod" button to pull requests (defaults to false)
    addBadge: false
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: prebuilt-in-gitpod

vscode:
  extensions:
    - sonarsource.sonarlint-vscode
    - esbenp.prettier-vscode
